### ISSUE TITLE
Yandex Transport in HA

### ISSUE THREAD

**Issue by alexreddy78** [devbis/aioymaps#2]
Dear Ivan,

Would you be so kind and see if you can fix an error in Yandex Transport integration, starts from 2023.9.0 

Error while setting up yandex_transport platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/yandex_transport/sensor.py", line 60, in async_setup_platform
    await ymaps.set_new_session()
  File "/usr/local/lib/python3.11/site-packages/aioymaps.py", line 97, in set_new_session
    self._config[PARAMS][CSRF_TOKEN_KEY] = result.group(1)
                                           ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

It was working in 2023.8 version, even captcha was not a problem, as I did request to update sensor each 30 minutes.

BRGDS
